package net.minestom.server;

/**
 * AUTOGENERATED by ConstantsGenerator
 */
interface MinecraftConstants {
    String VERSION_NAME = "1.21.2-pre5";

    int PROTOCOL_VERSION = 1073742041;

    int DATA_VERSION = 4077;

    int RESOURCE_PACK_VERSION = 42;

    int DATA_PACK_VERSION = 57;
}
